#!/bin/bash

DIRECTORY=`dirname $0`
export PYTHONPATH=$DIRECTORY:$DIRECTORY/gum:$PYTHONPATH

if test -z $@; then
    files=`find gum -name '*.py'`;
else
    files=$@
fi

for f in $files; do
    echo ""
    echo -e '\E[37;44m'"\033[1mpython $f\033[0m"
    python2 $f
    if [[ ! $? == 0 ]]; then
	echo -e '\E[31;40m'"\033[1mFailed \033[0m"
    fi
done
